### ISSUE TITLE
Clan Issuses 

### ISSUE THREAD

**Issue by MrRowey** [FAForever/website#322]
After asking a few people what the issues are with the clans currently here are a few points I received

- [ ] Invite link expire inconsistently
- [ ] Unable to Request to join a clan (then a mass approval/decline can be done)
- [ ] Autocomplete for name search is inconsistent when trying to find players
- [ ] Show the web address to copy easier.
- [ ] Be able to add Managers to a clan to be able to create Invite links / Approve join requests
- [ ] able to set clan links to not expire
- [ ] Unable to transfer Ownership of the clan to a player
- [ ] more filter options for all clans

**Comment by MrRowey** [comment]
#320 can be closed with this post

**Comment by Rackover** [comment]
This probably warrants to create several different issues rather than everything at once in a single one. This way not only can people add more informations as they go on individual problems, it also prevents from grouping together high priority issues, low priority issues, feature requests, and so so :)  

If you would be so kind as to create the issues independently and closing this one (and reopening #320 aswell i suppose) I will gladly look into the more criticals (clan transfer and others).  Some of these also need more informations, which will be easier to provide on separate issues 🙂

**Comment by Rackover** [comment]
This issue has been superseeded by the issues referenced above, please add more issues if more feature requests / bugs are requested or found. Some of these bullet points I did not understand what they mean, so feel free to recreate them as independent issues! ♥

**Comment by Rackover** [comment]
Reopened this one too - forgot to mention it:  https://github.com/FAForever/website/issues/320
