### ISSUE TITLE
Active Players Stats on Landing page

### ISSUE THREAD

**Issue by MrRowey** [FAForever/website#326]
The stats showing the active games and and how many people are online has disappeared in changes that I have made that I did not notice. need to revisit all the changes to see where I remove this

**Comment by Rackover** [comment]
![image](https://user-images.githubusercontent.com/33836535/161329160-a0bf6a79-90ce-4489-b170-eb175c079687.png)

![image](https://user-images.githubusercontent.com/33836535/161329763-355023f3-1d30-4675-8e48-8b30e6819759.png)

![image](https://user-images.githubusercontent.com/33836535/161329779-78d51157-7238-4cae-bfaa-04bdfb40b64c.png)

Interpolation fails because this critical setting is missing: 
https://github.com/FAForever/website/blame/b7a85dca5dd8ca31bbc643c9c44ab8359a0279e3/routes/views/index.js#L33

Has been removed by this commit:
https://github.com/FAForever/website/commit/b58580008b3dc19f60c0b364e127049b09a6badb

Along with a few other things that I think are essential (the flash errors you removed are used to display login error & clan app errors if I remember correctly)

You can fix this by simply adding this back
```
    // Render the view
    res.render('index', {flash: flash, refreshCountersSeconds: parseInt(process.env.PLAYER_COUNT_UPDATE_INTERVAL)});
```

but unless the flash errors have become unused throughout the whole website (something to check for thoroughly) then yo should probably also add them back because they will cause other issues elsewhere

```
    let flash = {};

    if (req.query.flash) {
        let buff = Buffer.from(req.query.flash, 'base64');  
        let text = buff.toString('ascii');

        try {
            flash = JSON.parse(text);
        } catch(e) {
          console.error("Parsing error while trying to decode a flash error: " + text);
          console.error(e);
          flash = [{msg: "Unknown error"}];
        }
    }
```

from where it was taken (index.js in website\routes\views)

Look at git blame on index.js to check the previous file structure & where to put the things

and you should be good for a test & deploy 🙂

**Comment by JaviTrek** [comment]
Thanks for the response @Rackover , I've been toying with the new frontend for the website and was wondering what were the flash messages for lol. Thanks alot for the detailled answer!

**Comment by MrRowey** [comment]
@Rackover Clans need a whole new rework as they work like 20% of the time and for the Login side, it is all done by the API now and not on the website itself. I was aware that I broke the current player statistic and just have not fixed it due to time and the fact was focusing on the new Frontend and will integrate this counter onto that rather than the one that's going to be replaced. the aim is to only fix the current site with Critical/ security fixes until were add the new front end.

**Comment by Rackover** [comment]
I think given it's a litteral one-liner it should neither delay the work on the "new frontend" nor endanger the website to add this back & deploy it as soon as possible to make sure users can enjoy a functional website while the new one is in the works 😅

**Comment by MrRowey** [comment]
Feel free to make the changes and ill merge them in :)

**Comment by Rackover** [comment]
[Sure](https://github.com/FAForever/website/pull/365)

It's a shame the website is going away, it's still looking pretty good and if most bugs are like this one, their lack of fixes could have more to do with eagerness to rewrite-it-all-from-scratch faf-style than with any sort of engineering challenge :v

As long as we don't get big ugly fonts, animated parts and pretentious one-liners on the front page I suppose it'll be fine 😛

EDIT :  oh be sure to test it, I don't have a FAF dev setup any more and even though it looks good maybe it won't run properly because of other changes i have not anticipated (env file changes for example?  did not check)

**Comment by MrRowey** [comment]
@Rackover Feel free to Take a look at the [test server](test.faforever.com) is where the current version of the new front end is located and provide any feedback is appreciated

And it passed the test and I've not touched the env for any of that timing accept removed the Twitch API stuff

**Comment by Rackover** [comment]
This issue is closed but the other one that rose from the PR is reported here: https://github.com/FAForever/website/issues/368
