### ISSUE TITLE
Website login takes you to link to steam page

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/website#419]
Whenever you login it takes you to the link to steam page. Not sure if intentional

**Comment by JaviTrek** [comment]
The issue is on the fullUrl on express.js, it doesn't actually set itself back to '/' (the home page) but instead remembers the previous URL it saved. Therefore when an user visits a protected steam or password or username route, it keeps that as the redirect for the next user until someone goes to another route without logging in. Will undo fullURL for now and set it to just '/' which is the home page

**Comment by Sheikah45** [comment]
No remembering is the right choice. But this occurred for me just when I clicked on the login button

**Comment by JaviTrek** [comment]
Yes but right now I believe it is better to set it to home as a quick fix instead of letting our users being sent all over the place until I fix this.
