### ISSUE TITLE
Enhancement Request: Clarify Steam Onboarding Instructions to Include Game Visibility Requirement

### ISSUE THREAD

**Issue by magge-faf** [FAForever/website#538]
It would be helpful to mention in the onboarding linking process for Steam that not only the Steam account has to be set public, but the game itself has to public as well. Those are two different settings in Steam, which users are not always aware of.

This forum post shows the solution:

https://forum.faforever.com/post/54746

Maybe mention it here:

https://faforever.com/play

Or on whatever page you feel like it would work best.

Example - Maybe word it better by underlining that the game itself has its own private/public setting:

![image](https://github.com/FAForever/website/assets/101107758/86dbad57-e5ca-4dfd-99e2-4ccb7ec059d9)

**Comment by MostLostNoob** [comment]
It would make more since to update the info about Privacy Settings that's already on the actual [link page](https://www.faforever.com/account/link) to include all 3 items that need to be Public:

My Profile
Game Details
SCFA itself

![image](https://github.com/FAForever/website/assets/84600965/4cd0c9f5-6f48-42c9-a36c-e5935a9e9bba)

**Comment by beckpaul** [comment]
Images here need updating for the current version and will be adding a secondary section about ensuring that your game is also set to public.
